name: astrologer
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  intl:
  camera:
  provider:
  image_picker:
  connectivity:
  http:
  shared_preferences:
  sqflite:
  path_provider:
  rxdart:
  firebase_core:
  firebase_messaging: 6.0.16
  flutter_local_notifications:
  flutter_inapp_purchase: 2.2.0
  expandable:
  random_color:
  in_app_purchase: ^0.3.4+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/
