import 'package:astrologer/core/data_model/idea_model.dart';
import 'package:flutter/material.dart';

final String whyCosmos =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. \n It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).";

final List<IdeaModel> ideaModelList = [
  IdeaModel(
      'Self',
      [
        'Am I on the right path according to astrology and destiny? What would be a good path for me right now?',
        'Can you tell me more about myself? Sometimes I feel like I don\'t know what my real personality is?',
        'What does near future hold for me? Can I expect anything exciting in my life soon?',
        'Do people like to be around me?',
        'Does my chart indicate anything about realizing my life purpose',
        'How gemstones influene on our mind? How can I know which gemstone is suitable for me?',
        'Does my future hold anything big, like fame or signifacnt notable success?',
        'When is the best time to start a fitness program and quit smoking to avoid extra stress?',
        'I want to have a pet. Which animal will I be happy with?',
        'If the destiny is written, so what do the starts say about mine?',
        'What colors in clothes should I have more to save my inner energy, be more balanced, attract people?',
        'Can I ever become an astrologer? If I finish courses or special talent needed? Do I have a good intuition?',
        'Everything in my life is not going as planned. What is my ultimate destiny? What and who am I fated to become?',
        'Why do I face the same problems during my life?',
        'Do you recommend any mantras to clear my path?',
        'Am I addicted to food too much? How can I deal with it?',
        'I feel very empty and hopeless at the moment. I have noe career, no partner, no big plans. I hope it changes for the better soon. Can you advise something?',
        'What are strong and weak sides of my personality? Which qualities should I improve in myself?',
        'Do you have any advice for meditations, mantras or gems that can increase positive effect on me at the current moment?',
        'Do the stars and planet have good advice for me how to make my will, confidence and self-love stronger?',
        'Do I need to lose any weight or change anything in my appearance?',
        'What\'s best for me according to Vedic astrology, should I focus on career, continuing my education, or having a family?',
        'I feel like I\'m a perfect woman - pretty, smart, loving, ambitious. But I never attract men on my level and it\'s painful. I don\'t want to be alone',
        'Does someone have a black magic, evil eye or voodoo doll on me? It looks like I\'ve had less luck lately. What is going on?',
        'How long will this difficult period continue? Can you recommend a gemstone to help me with motivation?',
        'What kind of sports activities suit me best?',
        'According to my birth chart and all the information you get from it. Would I make a good leader?',
        'Are there people who negatively influence me?',
        'Does destiny love me? Or did I miss my destiny? Where am I supposed to be?',
        'I have been singing and songwriting since childhood. Some music labels suggest me contracts, am I ready? Which can I devote?',
        'How to deal with all the stress I have?',
        'Everyone has a purpose in life. How do I know what is mine?',
        'Does it look like that I need to find myself spiritually? I feel llike i do not know what direction to take in my life. Whic path is better for me?',
        'I play in school performances. Can I become famous actress if I move to Hollywood? Or better to concentrate on other fields?',
        'Do you think I have a greater purpose in life? Was I destined to become a light, leader or savior?',
        'Do coffee and sugar really reflect on me? Will I notice real improvements if refuse these products?',
        'People treat me bad, hope that it will improve but it\'s not. Because of this I can see no positive future. What can you advise me?',
        'What is the thing I need to do for myself to start becoming truly happier?',
        'Do I have good intuition? Can I really sense spirits? Sometimes I have dreams of things before it happens. Do I have potential in spirituality?',
        'Everyone is married with children and it\'s a dream of mine and I am scared that it will never happen. What if it doesn\'t?',
        'I always expect too much from people around me. Is something wrong with them or I really expect too much? Can you show me the way to stop unrealistic expectations?',
        'How can I learn to accept and love all of myself especailly those aspects of who I am that I judge and feel ashamed about?',
        'Nothing has gone right for me for the last couple of years. When will things improve?',
        'Do I have a curse or bad luck and how can I have good luck from this point?',
        'The extreme responsibilities are causing me great anxiety. Will this end or is it just a part of my destiny that never will change?',
        'Everything is changing at once for me. I don\'t know I will be able to keep myself through it all. What does my birth chart say?',
        'I\'m having a difficult time understanding my purpose in life and my true calling. Do you have an idea of the direction i should go?',
        'Do you have any inspirational news from my chart for the upcoming month?',
        'What am I here to learn in this life? What is the mission of my life?',
        'I am a musician. I play musical instruments and sing. Will I become a famous musician one day?',
        'Am i going to have a long and happy life? Am I gonna have the life I want?',
        'I believe my destiny is to help people, is it really so? Which areas should I choose, according to the natal chart?',
        'I have a classmate meeting this weekend and really afraid to go because 10 years have passed and i didn\'t do any outstanding things in my life.',
        'Could you advise me a crystal or stone to wear that would help give me confidence or a positive attitude?',
        'Is now an auspicious time for personal growth? If so, what areas might I focus on?',
        'Do I have any future in the professional sport? How can I improve myself in this field?',
        'I feel like my motivation adn influence of the planets are strongly driving me in the right direction now. I am wondering what is my next major turn.',
        'What is my lucky number?',
        'I\'m feeling very depressed, stressed out and unmotivated to work, what\'s wrong with me? Please help me cope more effectively',
        'Can you guide me in regard to what is going in my mind and my heart?',
        'I\'ve been feeling a bit lazy and less production lately. When will I start being productive again? What is it going to take to get motivated?',
        'Am I where I am supposed to be at this point in my life? What would be a good path for me right now?',
        'Can I get my dream body someday? How can I get the courage to make it possible?',
        'What is the best lifestyle for me for spiritual growth? What practises are the best for me, according to natal chart?',
        'People tell that I\'m very difficult in making decisions. Is it really so?',
        'Which colors can bring me extra luck tomorrow?',
      ],
      iconData: Icons.insert_emoticon),
  IdeaModel(
      'Love',
      [
        'When will I meet the true love of my life?',
        'Am I going to be in a new relationship soon?',
        'Should I move in with my boyfriend',
        'What should I do right now and in the coming months to assure that my relationship will move to the next level?',
        'Why did we break up last year?',
        'Will it be good for me if I get back with my Ex?',
        'How many times will I meet a compatible potential life partner?',
        'Will my husband stay loyal and faithful for the rest of our lives?',
        'What does my birth chart show about my relationship this year? What can I do to improve it?',
        'What are the things t oavoid in my relationship with my boyfriend?',
        'Why do I always come back to him?',
        'I started a new relationship, but I still think about my Ex, how to finish this connection?',
        'Is there anyone loving me secretly? Or is interested in me right now?',
        'Am I gonna meet someone new today?',
        'Is my current partner the person I will spend all my life with?',
        'Is my current boyfriend capable of true love and being a good partner?',
        'Does my boyfriend still keep in touch with his Ex?',
        'Is my Ex meeting someonw now?',
        'Why am I single?',
        'I am looking for once in a lifetime soulmate. When will I meet him?',
        'Do you think that the connection I felt today with someone new will end up into something good?',
        'According to my birth details, how compatible am I with my current boyfriend?',
        'Am I making right decision breaking up with my boyfriend',
        'I think that my boyfriend is unfaithful, should I really worry about something or it\'s all just my imagination',
        'I feel really heartbroken. What should I do?',
        'How does my love life look this year?',
        'Is it possible for me and my ex to be good friends?',
        'The guy I like promised me to text me, but still didn\'t. Should I connect him first?',
        'When will I get married?',
        'When will I have kids?',
        'Is my boyfriend losing feelings for me? I feel that something has changed between us. What happened?',
        'If our relationship ends, who will be the one to make a decision?',
        'How long will the relationship with my current boyfriend last?',
        'Does my boyfriend want to be a better man for me? Does he want to change?',
        'What kind of person should I marry?',
        'Do I know my future boyfriend already? Is he the one I already know?',
        'Will my boyfriend make a proposal this year? When will we become engaged?',
        'What is my purpose in his life? Will we be a couple someday or just stay good friends?',
        'He never invites me to his family dinners, what does it mean? He keeps me in a secret or doesn\'t love me?',
        'Did I make the right decision to stay with my current partner and will I still be able to grow spiritually with him?',
        'I got a proposal from my boyfriend. Should I agree? Will our marriage be happy?',
        'How to get rid in a right way of a guy who is in love with me but I feel nothing for him?',
        'I just broke up with my boyfriend, but I really want him back. Is he my future husband and does he still love me?',
        'Do I need to worry about anything from his past? Can I trust him? Is he a good person?',
        'I think that I fell in love with my colleague. Should I tell him about my feelings? Is it a right time?',
        'Should I message him and tell that i miss him? Is that a good idea? Would it bring him to me faster?',
        'Is it good idea to go for a date tomorrow with...?',
        'Will I marry a millionaire?',
        'Will I get pregnant this year?',
        'What name should I choose for my first child? Could you advise me on how to select it?',
        'I\'m in love with a married man. He says taht he is divorcing soon. Is it really so? Will he be with me or stays with his wife?',
        'I and my boyfriend are in different locations now. Will we be together anyway?',
        'Can you check if my boyfriend is being faithful?',
        'I met a guy from the internet and he asked me out for a date. Should I agree? How can I trust him?',
        'Does the guy I met today likes me as more than a friend?',
        'Can I trust him to be faithful even before we are officially in a relationship? How do I know that?',
        'Every time I get to a point where it feels we are getting closer, it seems he pull back, why does he do that?',
        'Can I and my boyfriend ever manage to understand each other?',
        'Can I trust my boyfriend and let him spend separately the upcoming holidays?',
        'I have issues with my marriage. I am not happy with our relationship. Would I find happiness in another relationship or should I stay in the marriage?',
        'I am a divorce. Will I marry again? When?',
        'How many children will I have during my whole life?',
        'I am single right now and afraid if I agree for the relationship it will prevent my career growth, what should I do?',
        'What date is the best for my wedding this year?',
        'I and my future husband are from different cities, which city should we choose for the wedding ceremony?',
        'Does my boyfriend love me as much as I do or he is with me just because of comfort and good financial situation?'
      ],
      iconData: Icons.favorite_border),
  IdeaModel(
      'Everyday life',
      [
        " Can I expect any type of surprises this week either good or bad? If so, what kind?",
        "Does it look favorable to have a cosmetic procedure tomorrow?",
        "Can I expect to hear from my friends today? Do you know how they may be feeling about me?",
        "Feeling nervous about my competition this weekend. Will I do ok? Is there anything I can do to ensure everything runs smoothly on the day?",
        "Will I go for a vacation in the beginning of June? Because I have some obstacles and tomorrow I will get the final result. What does my birth chart show?",
        "Can I have some insight as to what today holds for me?",
        "I plan to have some remodeling at home this year When is the best time to start?",
        "I have lost my wedding ring. When will I need to tell what happened? What is the best time and what will be the outcome?",
        "If I delete my profiles from all social medias. Will it make my life better?",
        "Is there a special alignment of things in a house to feel more happy and balanced inside?",
        "What is the best day to go shopping this month ?",
        "Does it look favorable and safe to have a long car drive tomorrow or better to postpone it?",
        "I told him today he needs to make a decision if he wants me or not. What will he choose?",
        "Why am I so sad this week? Can you give me some advice on how to feel better?",
        "According to my natal chart, what type of books should I read now?",
        "The buyer for my property backed out saying it was too expensive. what is your advice?",
        "When is the best time for me to have a new haircut?",
        "Can I ask for financial help from my friend today?",
        "Will I meet someone special if I go to the party on Friday?",
        "What kind of perfume or scented oils should I use to attract people?",
        "It is trendy to become vegetarian. Should I become? Will it really improve me?",
        "I like a guy for a long time and finally decided to ask him for a date. What is the best time tomorrow to call him? Or better to text?",
        "Do I have extra luck today? I need to accomplish a very important deal.",
        "I had a bad day yesterday. It was hard to control my feelings and emotions. How does this fall under my sign and tomorrow’s outlook?",
        "I plan to rent an apartment but hesitate between several variants. Where will I feel more comfortable and happy? And what is the best time to move?",
        "Should I buy a dog or adopt a homeless puppy?",
        "I worry that I won’t be able to make a clear decision if offered a promotion. Will I have to make the decision with my head or heart?",
        "Do you see how I can gain more motivation this week? I have a lack of energy or will to do anything. Why is that?",
        "Will the guy I like come to my birthday party this Friday?",
        "Did I make an impression on a colleague today that I met the last month?",
        "Can you tell me how the party I am hosting today will go? Will the party go off as planned? Will the guests of honor be pleased with the event?",
        "Did I make the right choice ordering movie tickets for tomorrow? Will we really have a good time?",
        "Can I give resignation letter today? I want to rest at home for 2 months then start work. Is this good idea?",
        "Can you tell me what colors should I wear today and tomorrow, in order to enhance romance and attraction?",
        "Did I make a correct decision about my romantic partner today? In regards to our future?",
        "Am I gonna have a good day at school today?",
        "What gemstones and colors should I wear for the graduation party?",
        "I have an audition tomorrow. What type of outfit will be lucky and beneficial for me to wear? Dress, pants, sporty or casual?",
        "Can I buy a new car today? Is it good time according to planetary alignments?",
        "A lot of people are not much positive with me today. Why is that happening to me? And what the solution?",
        "Should I go to the party tomorrow?",
        "For my birthday, I had a strange gift from my boyfriend. What did he mean?",
        "Will I become less stressed if I sleep more hours at night? Does my natal chart show why I have too much of stress lately?",
        "Should I accept my boyfriends best friend? I feel the friend has disrespected our relationship. Are there any positive support from the stars in this regard?",
        "Boy that I like is a baseball player. If I go on our a date with his baseball team t-shirt on me will it be ok?",
        "What did he think about my beautiful dress today? Did he feel jealous towards my Ex-boyfriend?",
        "I had a snake in my dream this night. What does it mean?",
        "I bought a really big and beautiful house and just moved there but I don’t feel happy and satisfied? Why is it happening?",
        "The event where I would have seen the guy I like tomorrow was canceled. Any other chances of hearing from him or seeing him?",
        "Did I do the right thing by quitting my job today? what’s going to happen next? I have terrible anxiety.",
        "Give me some positive news. I really need some hope and encouragement these days.",
        "hich months of the year will be good and important? Any major changes this year? Best times for big decisions?"
      ],
      iconData: Icons.card_giftcard),
  IdeaModel(
      'Education',
      [
        "Am I on the right educational path? What are good fields for me to study?",
        "Will I get admission into my choice of college this year?",
        "After achieving bachelor degree should I continue education or start working?",
        "It’s difficult for me to concentrate on studying process. What can I do to improve it?",
        "My parents want me to become a lawyer. But I don’t feel like I can be a successful one. What do you see in my birth chart?",
        "Currently, I am working as a professor. I want some development in my career and qualifications. Is it still possible?",
        "Does the teacher I work with this year have feelings for me? Will it affect my studies?",
        "I have a team project in university and really afraid that we will fail it because of some members. Can I really trust and be confident in them?",
        "Do my classmates think good of me? What do they say about me to other teachers?",
        "Can I bring my math grade up and pass before the semester ends? What is my education horoscope for this year?",
        "I would like to know what is best outlook on life for me. Should I focus on continuing my education or having a family?",
        "Can I become a famous personality in college? What fields should I focus on?",
        "Does the chart reflect anything about returning to formal education such as acquiring a masters degree?",
        "I failed exams to a medical school and it was my dream. Why did it happen?",
        "Will I be able to get my education abroad one day and settle there? When?",
        "Am I gonna make the high school soccer team?",
        "Should I go for MBA? Will it really help me to boost my career? My dream is to become a CEO one day.",
        "I am on the edge of exclusion from college and afraid to tell my parents about it. How will the situation turn out? Could you check when is the right time?",
        "I want to join university football team, if I train every day will I get the invitation?",
        "I got accepted into two colleges. How can I choose the best one for me? I am out of any idea how to make this decision.",
        "Will I pass my driving test? I don’t feel safe.",
        "I’m working as a teacher at school and have difficulties with my teenage students. How can I improve them?",
        "Can I get an internship this semester?",
        "I found a good job, but still a student and plan to leave the university. Should I really do it? What is my destiny in regard to my education?",
        "I have a communication problem with my professor, how can I manage it? If I need to talk frankly with him what is the best time when planets support me?",
        "Can you tell me if there will be someone in my classes that likes me this year? Do I have any classes with the guy who will ask me out?",
        "What does my math teacher think about me? I’m really talented in class, but I feel a little forgotten by him.",
        "Does the program director at my college want to hire me as an intern based on my yesterday interview?",
        "I graduated, but can’t find a job in my field. Should I keep on looking or should I go back to university and train for something else?",
        "I have a difficult relationship with my classmates. Why is this happening?",
        "If I get married this year will I be able to continue education?",
        "When will I find a job which satisfies my educational background or should I go to studies again?",
        "My boyfriend is leaving for another country to study, could we support our relationship, despite the distance or should I attend studies abroad as well?",
        "I study a lot but anyway get bad grades. Why is it happening? Will I complete my education?",
        "Have the teachers I have been working with saying good things about me to my professor?",
        "I think that my professor gives me low grades just because he doesn’t like me, is that true? If yes then what solution you see in accordance with my natal chart.",
        "I’m having difficulty in education. Should I finish masters as I am not happy in the current field?",
        "I would like to know if my grades will be good this semester.",
        "I’m confused about my future. I have problems to finish my master thesis because I don’t really like the law. What is my destiny?",
        "My teacher is unclear with essay requirements and in turn, my grade is suffering. Will I turn it around by the end of the semester?",
        "Do you see me going back to school in the near future? I had to end my semester because of financial reason. When will I be going back without worry?",
        "Due to mental struggles, my mistakes may have cost me the failure in university. What is the likeliness my professors will give me another chance to continue the year?",
        "Will I be able to get a higher education? What course of education should I enroll in?",
        "Currently attending school for my undergraduate degree. I have been doing well in my classes but one professor wants to fail me for attendance how do my chances look?",
        "I am not doing good in studies at the moment. Do my classmates respect me?",
        "I’m having important exams next week. Will I get a needed score? Will I get the scholarship this year ?",
        "I am a teacher now. What does my chart say about education? Should I get my masters in art education or pursue art therapy in the future?",
        "Don’t have achievements yet. I feel that I may fail my studies. Please check what field of education and career path is more favorable for me."
      ],
      iconData: Icons.book),
  IdeaModel(
      'Work',
      [
        "When will I get a job?",
        "Will I get a promotion at work this year?",
        "Is it a good idea to accept a new job offer now?",
        "I have just accepted a new job offer. How should I behave with my new co-workers? What will be the atmosphere in my new workplace?",
        "I have an important job interview tomorrow, is it a good date for the interview to be successful? What can I do to make it successful?",
        "I was promoted to a manager position, can you give me career guidance how to mentor it all correctly",
        "Can I be a good boss? Will people love me? What does my birth chart say?",
        "Why can’t I find a job? How to deal with it?",
        "I am having a problem at work with my boss. Do you think things will improve or will I have to quit?",
        "I didn’t receive even one invitation to the job interview during last 2 months. What is wrong?",
        "Should I accept a job offer in another city?",
        "I am a housewife and I feel really bored. But if I get a job, could I handle it? Will I be successful?",
        "Dismissals started to happen in my office, will it touch me?",
        "I had an important job interview today but didn’t get any feedback yet, how was it? Will they hire me?",
        "In what ways should I develop myself to come over interviews more efficient?",
        "Which days and time are the best for me to appoint a job interview?",
        "Sometimes I feel very confident during the interview and sometimes really lost and confused, why is this happening?",
        "I like a guy from my office, should I ask him out for a date or will it spoil our professional relationship?",
        "I want to get a job, but my husband doesn’t want me to work, what should I do?",
        "I feel I meant to do something big in life but I am having trouble figuring out what it is. Is it related to my career?",
        "I am afraid to agree with job promotion because of my colleagues would be jealous and might not support me. What should I do?",
        "I don’t like my job at all, how can I get a job of my dream?",
        "What does my birth chart show about my work atmosphere and career progress this year?",
        "Will I get a salary increase this year?",
        "I’ve had more than 10 job interviews but I didn’t receive any offers. What is wrong?",
        "People say that clothes matter during a job interview. What should I wear for the interview tomorrow? Colours? Some bringing luck gemstones?",
        "I have received several job offers. Which one should I choose?",
        "I think my boss offers me a promotion with a salary increase because he likes me. If I agree will he want to get something instead?",
        "One of my colleagues always misrepresents me. Why does she do it? How to deal with it?",
        "I change my workplace really often. I can’t understand why. What type of job suits me best according to my natal chart?",
        "I am tired of sitting at home. I want to become a fitness instructor. Will I be good in it?",
        "I’m working in my current place for three years and feel boring. When is the best time to start searching for a new job?",
        "Should I amplify my qualities and experience in my CV or is it better to write everything truthfully?",
        "Will I be asked to become a manager this year?",
        "I had a dream that I will fail tomorrow’s job interview, will it be so?",
        "Which gemstone should I have with me during the interview to feel confident?",
        "I have an awkward relationship with the boss. What is the reason for that according to astrology?",
        "I think my colleagues don’t like me, is it really so? What can I do to improve the situation?",
        "I graduated 1-2 years ago and I cannot seem to find a job in my field. Should I keep on looking or should I train for something else?",
        "Is it a good time to change my workplace now?",
        "I’m going to a business trip next month, how should I prepare for that? Will it be efficient for me?",
        "I have a tough phase in my workplace. Could you suggest a suitable solution that leads to some achievements?",
        "When is a good time to retire?",
        "I want to get a job abroad. When will I be able to do that?",
        "Did upper management understand my concerns today and will there be changes? Will they take me seriously?",
      ],
      iconData: Icons.work),
  IdeaModel(
      'Money',
      [
        "Tell me what important thing should I know about money in my future.",
        "Will I become rich one day?",
        "I feel like my husband is keeping secret our financial situation, is he? Is it better than he tells me or worse?",
        "Will I ever be financially independent of my family?",
        "I am going to take out a loan, when is the best date to apply for it?",
        "Will I have enough money to buy my own house one day?",
        "I need some money, is it better to borrow from friends or take a loan from a bank?",
        "Will I be able to get a loan from a bank?",
        "A lot of people tell me that I will not ever be able to save money. Is that true?",
        "My friend wants me to lend him some money? Will it affect our friendship?",
        "Why am I facing debts and losses?",
        "Will I get a sudden fortune or lottery luck?",
        "Can u tell me about money flow throughout my life?",
        "What can I do to improve my financial situation?",
        "When is the best time to buy a car?",
        "Should we have one account or two with my husband?",
        "My husband says that we should be saving more. Should we?",
        "Should I buy a really expensive present for my boyfriend’s birthday to prove that I love him?",
        "I earn more than my husband and I think he feels sad and angry about it, Is it really so?",
        "Will my life improve If I start to give money to charity?",
        "My mind is always on my money, doesn’t it make me a bad person?",
        "Will I get an inheritance and if yes then when?",
        "How should I start saving for college now? Or will my financial situation improve?",
        "I saved up some money, should I keep them in a bank or invest?",
        "Should I save up some money secretly from my husband?",
        "I’m a housewife and my husband gives me money, I want more but afraid to ask him, what should I do?",
        "My husband spends a lot of money. Does he spend it on other women?",
        "Is there any financial problems in my future. How much money should I save?",
        "My husband borrowed a lot of money for business. We are struggling to pay back. Are there in the future any more issues like this?",
        "When will my money situation be stable?",
        "Will we be able to afford a baby in the upcoming year?",
        "I have a lot of arguments with my husband in regard to money recently. What is the reason for that?",
        "Can we do our taxes ourselves or should we get them done?",
        "I date one guy but I always pay for both of us everywhere. Is he with me because of my money?",
        "Is it smart to buy a house in this market?",
        "The rent price is raised. Will I be able to find the same for the better price? Or should I agree to the raise?",
        "My boyfriend never leaves tips in a restaurant. Is that because he is greedy?",
        "I feel like I spend too much money on shopping. Is it really an obsession? Should I reduce my spendings?",
        "What job sectors I can earn the most? Should I change now?",
        "When is the best time to sell my house?",
      ],
      iconData: Icons.monetization_on),
  IdeaModel(
      'Business',
      [
        "According to my birth chart, can I be a good businessman?",
        "I want to run my own business. Which sphere should I choose? Where will I be more successful?",
        "When will be a good time to invest my money?",
        "If I open a store with handmade organic cosmetics will it be successful?",
        "Is it a good time to open my own business now? When is the best time to launch a new business to make it successful?",
        "I am tired being just an employee. Will I get a proposal for partnership? Or it is better to start my own business?",
        "I was asked to become a business partner of my friend. Should I agree?",
        "I am working on a big project at present. Will it be successful? Will I make money or lose money?",
        "I have just started a new business. It is very challenging and I have many doubts. How long will it be until I become profitable?",
        "I am successful in my current business but want to extend into other areas. Could you advise what other directions are good for me?",
        "I am a makeup artist. If I start online video blog will I become successful and famous?",
        "Should I invite other people to my business or make everything my own?",
        "Will it be the right decision to start a business with my relatives?",
        "I have tried a couple of times to start my own business but failed. Should I continue? What my birth chart say?",
        "I have a meeting with an important potential customer next week, will it be successful? What date and time will be the best for it?",
        "What are the weak sides of my business skills?",
        "I plan to open a public relation agency this year. Will I make it good and popular?",
        "My husband wants me to quit a business and take care of our kids. What should I do? Am I capable of doing both?",
        "Could you provide reading about next week in terms of my business? Especially if there are any new deals coming.",
        "Is it a good time to invest more money in an advertisement? Will it pay off and help my business to become more profitable?",
        "Why is my business not running well? When will it pick up?",
        "Can I completely trust my business partner?",
        "What will happen with my business in the upcoming year?",
        "I have a hairdressing salon and plan to open a massage salon as well this year. Will I be able to pay my loans?",
        "Should I hire a new assistant whom I interviewed today?",
        "Changes have been made in business and new people are on board. I want to know if this was the right decision and how well things will go from here?",
        "How can I motivate my employees to become more effective?",
        "My partners are reviewing new deal too long. Will they agree? What’s going on?",
        "The relationship with my business partner is going down. What is the reason and what can I do to improve them?",
        "There is a crisis in my business industry. What should I do, wait or try to sell now until it is completely down?",
        "I want to expand my business abroad. What countries are the best for it?",
        "I’m a fitness instructor. Will I open a network of gyms in the future?",
        "Can I bear more risk in business this year? Should I move forward for expansion or should I quit and keep a low profile?",
        "If I increase the cost of my services how will customers react? Will they still stay with me?",
        "Will I have a tax audit this year?",
        "Should I hire consulting company to help to solve my company problems or try to do it just by myself?",
        "I had very important negotiations today. Will we make the deal?",
        "I want to try to start up a small fashion business. According to my birth chart, Am I supposed to be good in that?",
        "Is there a threat of appearing new competitors in my field this year?",
        "Unexpectedly I am struggling with my business recently and despite many efforts, it seems that there is a bad luck. How long will it continue?",
        "I was asked to sell my business. Should I do it and take the money or continue working on it?",
        "I want to retire. Should I sell my business or find a partner who will take care of it?",
        "What does Vedic astrology say about my luck in trading ? If this is not suitable, please recommend me business sector for more profit.",
        "I want to run my own jewelry business. Which gemstones can I sell the best?",
        "If I merge my company with my major competitor will it pay off in the long-term perspective?",
        "My business is in downgrade period. Is it better to close it or find money and try to revive it?",
      ],
      iconData: Icons.business),
];
