import 'package:astrologer/core/data_model/idea_model.dart';
import 'package:flutter/material.dart';

final String whyCosmos =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. \n It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).";

final List<IdeaModel> ideaModelList = [
  IdeaModel(
      'Self',
      [
        ' When will I achieve the goal of my life ?',
        ' Will my aim turn out as my career ?',
        ' What can i do to be happy ?',
        ' I love singing and dancing , if I give it time  will it affect my career ?',
        ' I am introvert , but I want to be an extrovert. How can I be ?',
        ' I don\'t know what i am , my actual personality. Can you tell me more about myself ?',
        ' I am giving my best on my studies but still I cannot do well and cannot get things easily . how can i improve my study ?',
        ' I have started a  new business. Will I succeed in it ?',
        'Which is the lucky colour for me ?',
        'How can I attract people toward me ?',
        'I am too much addicted to porn ,how can I let my mind free of porn ?',
        'It\'s very difficult for me to concentrate on a particular subject , what can I do to increase my concentration power ?',
        'Which stone rings should I wear ?',
        'At what age will I be financially independent ?',
        'I don\'t eat heavy foods but my weight is increasing excessively. How can I lose my weight ?',
        'I easily get excited for my new plan but also get depressed if there occur minor problems . How can I have control over such emotions ?',
        'Everyone has both strong as well as weak sides , I can only find my weak sides . What are my strong sides ?',
        'How can I get rid of people who have a negative influence on me ?',
        'Could you recommend any mantras, meditation , gemstones to clear my path ?',
        'How can I overcome the problems that I face in my life ?',
        'If anything wrong happens , i feel very low ,how can i feel better in such situations ?',
        'I am very short tempered. Do planets and stars have good advice for me to control anger ?',
        'I love football ,will it suit me ?',
        'Will I be a  good leader in my life according to my natal chart ?',
      ],
      iconData: Icons.insert_emoticon),
  IdeaModel(
      'Love',
      [
        'When will I meet my first love?',
        'Will I ever find true love?',
        'Will it be okay to move on with my present boyfriend ?',
        'Why am I not getting a perfect partner?',
        'At what age will I marry ?',
        'What will be the profession of my future husband ?',
        'How much older will my partner be than me ?',
        'How many children will I have ?',
        'Different complications have arisen in my relationship ?',
        'How can I solve those complications ?',
        'I easily create different doubts in my mind about my partner ,how can I make my mind free  of doubts ?',
        'In how many relationships will I be through out my life ?',
        'Will I ever find a partner of the same personality as mine ?',
      ],
      iconData: Icons.favorite_border),
  IdeaModel(
      'Everyday life',
      [
        'Will‌ ‌I‌ ‌hear‌ ‌life‌ ‌changing‌ ‌news‌ ‌today?‌ ‌',
        'I‌ ‌had‌ ‌applied‌ ‌for‌ ‌a‌ ‌lottery‌ ‌ticket.‌ ‌Will‌ ‌I‌ ‌win‌ ‌the‌ ‌lottery?‌‌',
        'I\'m‌ ‌very‌ ‌sick,‌ ‌will‌ ‌my‌ ‌friend‌ ‌visit‌ ‌me‌ ‌today?‌',
        'I‌ ‌had‌ ‌a‌ ‌dream‌ ‌last‌ ‌night,I‌ ‌found‌ ‌myself‌ ‌climbing‌ ‌a‌ ‌high‌ ‌mountain.‌ ‌What‌ ‌does‌ ‌it‌ ‌mean?',
        'I‌ ‌have‌ ‌a‌ ‌big‌ ‌house,‌ ‌huge‌ ‌property,‌ ‌successful‌ ‌business‌ ‌but‌ ‌still‌ ‌I\'m‌ ‌not‌ ‌satisfied,‌ ‌why‌ ‌am‌ ‌I‌ ‌feeling‌ ‌so?‌‌',
        'I‌ ‌had‌ ‌an‌ ‌argument‌ ‌with‌ ‌my‌ ‌boss‌ ‌so‌ ‌I‌ ‌left‌ ‌my‌ ‌job‌ ‌today,‌ ‌will‌ ‌I‌ ‌get‌ ‌a‌ ‌new‌ ‌job‌ ‌soon‌ ‌?‌‌',
        'These‌ ‌days‌ ‌i‌ ‌have‌ ‌been‌ ‌feeling‌ ‌low,‌ ‌so‌ ‌how‌ ‌can‌ ‌i‌ ‌swing‌ ‌my‌ ‌mind?‌‌',
        'I\'m‌ ‌selected‌ ‌for‌ a‌ ‌speech‌ ‌competition‌ ‌but‌ ‌I‌ ‌get‌ ‌so‌ ‌nervous‌ ‌when‌ ‌I‌ ‌am‌ ‌in‌ ‌front‌ ‌of‌ ‌a‌ ‌huge‌ ‌mass,‌ ‌how‌ ‌can‌ ‌I‌ ‌deal‌ ‌with‌ ‌it?‌‌',
        'Today‌ ‌is‌ ‌my‌ ‌birthday‌ ‌,can‌ ‌I‌ ‌start‌ ‌a‌ ‌new‌ ‌business?‌ ‌',
        'I\'m‌ ‌going‌ ‌to‌ ‌a‌ ‌party‌ ‌tonight,‌ ‌which‌ ‌dress‌ ‌should‌ ‌i‌ ‌wear‌ ‌to‌ ‌attract‌ ‌everyone‌ ‌?‌ ‌',
        'I‌ ‌have‌ ‌a‌ ‌crush‌ ‌on‌ ‌a‌ ‌cricketer‌ ‌and‌ ‌I‌ ‌proposed‌ ‌to‌ ‌him‌ ‌today.‌ ‌Will‌ ‌he‌ ‌accept‌ ‌my‌ ‌proposal‌ ‌?‌ ‌',
        'Should‌ ‌i‌ ‌go‌ ‌to‌ ‌the‌ ‌party‌ ‌tonight‌ ‌?‌ ‌',
        'Should‌ ‌I‌ ‌go‌ ‌shopping‌ ‌this‌ ‌weekend‌ ‌?‌ ‌',
        'How‌ ‌can‌ ‌I‌ ‌align‌ ‌things‌ ‌in‌ ‌my‌ ‌room‌ ‌so‌ ‌that‌ ‌I‌ ‌can‌ ‌feel‌ ‌better?‌ ‌',
        'I\'m‌ ‌getting‌ ‌more‌ ‌addicted‌ ‌to‌ ‌social‌ ‌media‌ ‌these‌ ‌days,‌ ‌should‌ ‌i‌ ‌delete‌ ‌my‌ ‌social‌ ‌media‌ ‌account‌ ‌to‌ ‌focus‌ ‌on‌ ‌my‌ ‌studies?‌ ‌',
        'I‌ ‌have‌ ‌bought‌ ‌a‌ ‌new‌ ‌house,‌ ‌can‌ ‌I‌ ‌shift‌ ‌to‌ ‌it‌ ‌today‌ ‌?‌ ‌',
        'Today‌ ‌is‌ ‌my‌ ‌girlfriend\'s‌ ‌birthday.‌ ‌What‌ ‌present‌ ‌should‌ ‌I‌ give‌ ‌her‌ ‌to‌ ‌make‌ ‌her‌ ‌feel‌ ‌special?‌ ‌',
        'Should‌ ‌I‌ ‌get‌ ‌a‌ ‌haircut‌ ‌this‌ ‌month?‌ ‌',
        'I‌ ‌have‌ ‌financial‌ ‌problems‌ ‌this‌ ‌week,‌ ‌can‌ ‌I‌ ‌ask‌ ‌for‌ ‌financial‌ ‌help‌ ‌from‌ ‌my‌ ‌neighbour‌ ‌today?‌ ‌',
        'I‌ ‌have‌ ‌made‌ ‌a‌ ‌bet‌ ‌for‌ ‌a‌ ‌football‌ ‌match‌ ‌today,‌ ‌will‌ ‌my‌ ‌team‌ ‌win?‌ ‌',
        'I‌ ‌love‌ ‌keeping‌ ‌pets‌ ‌at‌ ‌home‌ ‌but‌ ‌my‌ ‌mother‌ ‌doesn\' t‌ ‌want‌ ‌it,‌ ‌how‌ ‌can‌ I ‌ ‌convince‌ ‌her?‌ ‌',
        'Today‌ ‌is‌ ‌the‌ ‌new‌ ‌year.‌ ‌What‌ ‌surprise‌ ‌will‌ ‌i‌ ‌get‌ ‌from‌ ‌my‌ ‌best‌ ‌friend?‌ ‌',
      ],
      iconData: Icons.card_giftcard),
  IdeaModel(
      'Education',
      [
        "Am I on the right educational path? What are good fields for me to study?",
        "Will I get admission into my choice of college this year?",
        "After achieving bachelor degree should I continue education or start working?",
        "It’s difficult for me to concentrate on studying process. What can I do to improve it?",
        "My parents want me to become a lawyer. But I don’t feel like I can be a successful one. What do you see in my birth chart?",
        "Currently, I am working as a professor. I want some development in my career and qualifications. Is it still possible?",
        "Does the teacher I work with this year have feelings for me? Will it affect my studies?",
        "I have a team project in university and really afraid that we will fail it because of some members. Can I really trust and be confident in them?",
        "Do my classmates think good of me? What do they say about me to other teachers?",
        "Can I bring my math grade up and pass before the semester ends? What is my education horoscope for this year?",
        "I would like to know what is best outlook on life for me. Should I focus on continuing my education or having a family?",
        "Can I become a famous personality in college? What fields should I focus on?",
        "Does the chart reflect anything about returning to formal education such as acquiring a masters degree?",
        "I failed exams to a medical school and it was my dream. Why did it happen?",
        "Will I be able to get my education abroad one day and settle there? When?",
        "Am I gonna make the high school soccer team?",
        "Should I go for MBA? Will it really help me to boost my career? My dream is to become a CEO one day.",
        "I am on the edge of exclusion from college and afraid to tell my parents about it. How will the situation turn out? Could you check when is the right time?",
        "I want to join university football team, if I train every day will I get the invitation?",
        "I got accepted into two colleges. How can I choose the best one for me? I am out of any idea how to make this decision.",
        "Will I pass my driving test? I don’t feel safe.",
        "I’m working as a teacher at school and have difficulties with my teenage students. How can I improve them?",
        "Can I get an internship this semester?",
        "I found a good job, but still a student and plan to leave the university. Should I really do it? What is my destiny in regard to my education?",
        "I have a communication problem with my professor, how can I manage it? If I need to talk frankly with him what is the best time when planets support me?",
        "Can you tell me if there will be someone in my classes that likes me this year? Do I have any classes with the guy who will ask me out?",
        "What does my math teacher think about me? I’m really talented in class, but I feel a little forgotten by him.",
        "Does the program director at my college want to hire me as an intern based on my yesterday interview?",
        "I graduated, but can’t find a job in my field. Should I keep on looking or should I go back to university and train for something else?",
        "I have a difficult relationship with my classmates. Why is this happening?",
        "If I get married this year will I be able to continue education?",
        "When will I find a job which satisfies my educational background or should I go to studies again?",
        "My boyfriend is leaving for another country to study, could we support our relationship, despite the distance or should I attend studies abroad as well?",
        "I study a lot but anyway get bad grades. Why is it happening? Will I complete my education?",
        "Have the teachers I have been working with saying good things about me to my professor?",
        "I think that my professor gives me low grades just because he doesn’t like me, is that true? If yes then what solution you see in accordance with my natal chart.",
        "I’m having difficulty in education. Should I finish masters as I am not happy in the current field?",
        "I would like to know if my grades will be good this semester.",
        "I’m confused about my future. I have problems to finish my master thesis because I don’t really like the law. What is my destiny?",
        "My teacher is unclear with essay requirements and in turn, my grade is suffering. Will I turn it around by the end of the semester?",
        "Do you see me going back to school in the near future? I had to end my semester because of financial reason. When will I be going back without worry?",
        "Due to mental struggles, my mistakes may have cost me the failure in university. What is the likeliness my professors will give me another chance to continue the year?",
        "Will I be able to get a higher education? What course of education should I enroll in?",
        "Currently attending school for my undergraduate degree. I have been doing well in my classes but one professor wants to fail me for attendance how do my chances look?",
        "I am not doing good in studies at the moment. Do my classmates respect me?",
        "I’m having important exams next week. Will I get a needed score? Will I get the scholarship this year ?",
        "I am a teacher now. What does my chart say about education? Should I get my masters in art education or pursue art therapy in the future?",
        "Don’t have achievements yet. I feel that I may fail my studies. Please check what field of education and career path is more favorable for me."
      ],
      iconData: Icons.book),
  IdeaModel(
      'Work',
      [
        'I have already completed my education, when will I get a job ?',
        'I have been doing a job for 4 years but still i cannot fulfill all my needs. When will i get a good job?',
        'I had a huge business loss previous years, will it improve this year ?',
        'Which business should I start for a good income ?',
        'Is direct selling business good for me ?',
        'I put much effort into my job but still my boss complains a lot. Should i leave this job ?',
        'I have been working as a manager for five years, when will i get my promotion ?',
        'At what age will I get retirement ?',
        'I\'m going for a business trip next week, will it be successful ?',
        'I found a high profit job should I leave the previous one ?',
        'I\'m not getting a job as per my educational qualification. When will I get it ?',
        'I do my work well but i cannot face mass confidently. Which gemstone should I have to increase my confidence ?',
        'I proposed to a guy in my office today, will it affect our professional relationship ?',
        'I\'m very much satisfied with my career progress. How can I continue my progression at the same pace ?',
        'I get a job offer in another city but my husband does not want to go. What should i do ?',
        'According to my natal chart, how is my career progressing in my business ?',
        'I\'m not satisfied with the salary I\'m getting, can I apply for part time jobs too?',
        'How can I work for my personality development to foster my business ?',
        'What should I do to motivate and energize my employees ?',
        'I had a dream this night that I was swimming in clear water. Does it give any signs of my business ?',
        'My boss wants to make a relationship with me but I already have a boyfriend. How can I deal with this ?',
        'I\'m going to organize a grand event for my business this month , will it help to foster my business ?',
        'Which business should I start to earn the most ?',
        'Wherever I make investment, there occurs loss . Why is this happening? Is this because of planets, in my life ?',
        'I have many ideas regarding my business but I\'m not able to express it in the correct way . How can I manage it ?',
      ],
      iconData: Icons.work),
  IdeaModel(
      'Money',
      [
        'Will I become the world\'s richest person one day ?',
        'My expenditure is much more than my income. How can I make a  balance ?',
        'In which profession will I get more money?',
        'How much money I have, I spend them all, why can\'t I make savings?',
        'At what age will I be financially independent ?',
        'I\'m going through financial problems these days, should I take a loan?',
        'Should I invest my money to get more money in the share market ?',
        'When will I have as much money as to buy a house?',
        'My friend is asking me for money, will he return it in time ?',
        'I give all my income to my family, should i save up money secretly from my family ?',
        'My husband spends a lot of money. Does he have other women on whom he is spending ?',
        'I\'m not satisfied with my income, it\'s not even sufficient to run my family. How can I earn more money?',
        'Whenever I go on a date with my girlfriend she pays her bills on her own. Does she think I\'m poor ?',
        'My house owner increases the rent price two times a year. Should I find a new place to get shifted or should I agree to the raise ?',
        'Should i sell my house to buy another big house?',
        'I don\'t want go on a trip with my greedy friends but they are forcing me to go. How should I manage them ?',
        'Why are my neighbours so jealous with my success ?',
        'When will my family financial situation be stable ?',
        'Will me and my husband be able to afford a body this year ?',
        'I should always ask my husband for money. Should i do a job on my own?',
        'Will I face money problems in the future ?',
        'I\'m not able to fulfill the needs of my children, how can I increase my income ?',
        'Should I buy a car this week ?',
        'When I go shopping, I spend all my money. How can I control it ?',
        'I\'m staying at a hostel and my parents send me money once a month. Which i spend soon and later have scarcity of money. How can I manage money?',
      ],
      iconData: Icons.monetization_on),
];
