import 'package:astrologer/core/data_model/idea_model.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

final String whyCosmos =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum. \n It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).";

final List<IdeaModel> ideaModelList = [
  IdeaModel(
      'Self',
      [
        'Am I on the right path according to astrology and destiny? What would be a good path for me right now?',
        'Can you tell me more about myself? Sometimes I feel like I don\'t know what my real personality is?',
        'What does near future hold for me? Can I expect anything exciting in my life soon?',
        'Do people like to be around me?',
        'Does my chart indicate anything about realizing my life purpose',
        'How gemstones influene on our mind? How can I know which gemstone is suitable for me?',
        'Does my future hold anything big, like fame or signifacnt notable success?',
        'When is the best time to start a fitness program and quit smoking to avoid extra stress?',
        'I want to have a pet. Which animal will I be happy with?',
        'If the destiny is written, so what do the starts say about mine?',
        'What colors in clothes should I have more to save my inner energy, be more balanced, attract people?',
        'Can I ever become an astrologer? If I finish courses or special talent needed? Do I have a good intuition?',
        'Everything in my life is not going as planned. What is my ultimate destiny? What and who am I fated to become?',
        'Why do I face the same problems during my life?',
        'Do you recommend any mantras to clear my path?',
        'Am I addicted to food too much? How can I deal with it?',
        'I feel very empty and hopeless at the moment. I have noe career, no partner, no big plans. I hope it changes for the better soon. Can you advise something?',
        'What are strong and weak sides of my personality? Which qualities should I improve in myself?',
        'Do you have any advice for meditations, mantras or gems that can increase positive effect on me at the current moment?',
        'Do the stars and planet have good advice for me how to make my will, confidence and self-love stronger?',
        'Do I need to lose any weight or change anything in my appearance?',
        'What\'s best for me according to Vedic astrology, should I focus on career, continuing my education, or having a family?',
        'I feel like I\'m a perfect woman - pretty, smart, loving, ambitious. But I never attract men on my level and it\'s painful. I don\'t want to be alone',
        'Does someone have a black magic, evil eye or voodoo doll on me? It looks like I\'ve had less luck lately. What is going on?',
        'How long will this difficult period continue? Can you recommend a gemstone to help me with motivation?',
        'What kind of sports activities suit me best?',
        'According to my birth chart and all the information you get from it. Would I make a good leader?',
        'Are there people who negatively influence me?',
        'Does destiny love me? Or did I miss my destiny? Where am I supposed to be?',
        'I have been singing and songwriting since childhood. Some music labels suggest me contracts, am I ready? Which can I devote?',
        'How to deal with all the stress I have?',
        'Everyone has a purpose in life. How do I know what is mine?',
        'Does it look like that I need to find myself spiritually? I feel llike i do not know what direction to take in my life. Whic path is better for me?',
        'I play in school performances. Can I become famous actress if I move to Hollywood? Or better to concentrate on other fields?',
        'Do you think I have a greater purpose in life? Was I destined to become a light, leader or savior?',
        'Do coffee and sugar really reflect on me? Will I notice real improvements if refuse these products?',
        'People treat me bad, hope that it will improve but it\'s not. Because of this I can see no positive future. What can you advise me?',
        'What is the thing I need to do for myself to start becoming truly happier?',
        'Do I have good intuition? Can I really sense spirits? Sometimes I have dreams of things before it happens. Do I have potential in spirituality?',
        'Everyone is married with children and it\'s a dream of mine and I am scared that it will never happen. What if it doesn\'t?',
        'I always expect too much from people around me. Is something wrong with them or I really expect too much? Can you show me the way to stop unrealistic expectations?',
        'How can I learn to accept and love all of myself especailly those aspects of who I am that I judge and feel ashamed about?',
        'Nothing has gone right for me for the last couple of years. When will things improve?',
        'Do I have a curse or bad luck and how can I have good luck from this point?',
        'The extreme responsibilities are causing me great anxiety. Will this end or is it just a part of my destiny that never will change?',
        'Everything is changing at once for me. I don\'t know I will be able to keep myself through it all. What does my birth chart say?',
        'I\'m having a difficult time understanding my purpose in life and my true calling. Do you have an idea of the direction i should go?',
        'Do you have any inspirational news from my chart for the upcoming month?',
        'What am I here to learn in this life? What is the mission of my life?',
        'I am a musician. I play musical instruments and sing. Will I become a famous musician one day?',
        'Am i going to have a long and happy life? Am I gonna have the life I want?',
        'I believe my destiny is to help people, is it really so? Which areas should I choose, according to the natal chart?',
        'I have a classmate meeting this weekend and really afraid to go because 10 years have passed and i didn\'t do any outstanding things in my life.',
        'Could you advise me a crystal or stone to wear that would help give me confidence or a positive attitude?',
        'Is now an auspicious time for personal growth? If so, what areas might I focus on?',
        'Do I have any future in the professional sport? How can I improve myself in this field?',
        'I feel like my motivation adn influence of the planets are strongly driving me in the right direction now. I am wondering what is my next major turn.',
        'What is my lucky number?',
        'I\'m feeling very depressed, stressed out and unmotivated to work, what\'s wrong with me? Please help me cope more effectively',
        'Can you guide me in regard to what is going in my mind and my heart?',
        'I\'ve been feeling a bit lazy and less production lately. When will I start being productive again? What is it going to take to get motivated?',
        'Am I where I am supposed to be at this point in my life? What would be a good path for me right now?',
        'Can I get my dream body someday? How can I get the courage to make it possible?',
        'What is the best lifestyle for me for spiritual growth? What practises are the best for me, according to natal chart?',
        'People tell that I\'m very difficult in making decisions. Is it really so?',
        'Which colors can bring me extra luck tomorrow?',
      ],
      iconData: Icons.insert_emoticon),
  IdeaModel(
      'Love',
      [
        'When will I meet the true love of my life?',
        'Am I going to be in a new relationship soon?',
        'Should I move in with my boyfriend',
        'What should I do right now and in the coming months to assure that my relationship will move to the next level?',
        'Why did we break up last year?',
        'Will it be good for me if I get back with my Ex?',
        'How many times will I meet a compatible potential life partner?',
        'Will my husband stay loyal and faithful for the rest of our lives?',
        'What does my birth chart show about my relationship this year? What can I do to improve it?',
        'What are the things t oavoid in my relationship with my boyfriend?',
        'Why do I always come back to him?',
        'I started a new relationship, but I still think about my Ex, how to finish this connection?',
        'Is there anyone loving me secretly? Or is interested in me right now?',
        'Am I gonna meet someone new today?',
        'Is my current partner the person I will spend all my life with?',
        'Is my current boyfriend capable of true love and being a good partner?',
        'Does my boyfriend still keep in touch with his Ex?',
        'Is my Ex meeting someonw now?',
        'Why am I single?',
        'I am looking for once in a lifetime soulmate. When will I meet him?',
        'Do you think that the connection I felt today with someone new will end up into something good?',
        'According to my birth details, how compatible am I with my current boyfriend?',
        'Am I making right decision breaking up with my boyfriend',
        'I think that my boyfriend is unfaithful, should I really worry about something or it\'s all just my imagination',
        'I feel really heartbroken. What should I do?',
        'How does my love life look this year?',
        'Is it possible for me and my ex to be good friends?',
        'The guy I like promised me to text me, but still didn\'t. Should I connect him first?',
        'When will I get married?',
        'When will I have kids?',
        'Is my boyfriend losing feelings for me? I feel that something has changed between us. What happened?',
        'If our relationship ends, who will be the one to make a decision?',
        'How long will the relationship with my current boyfriend last?',
        'Does my boyfriend want to be a better man for me? Does he want to change?',
        'What kind of person should I marry?',
        'Do I know my future boyfriend already? Is he the one I already know?',
        'Will my boyfriend make a proposal this year? When will we become engaged?',
        'What is my purpose in his life? Will we be a couple someday or just stay good friends?',
        'He never invites me to his family dinners, what does it mean? He keeps me in a secret or doesn\'t love me?',
        'Did I make the right decision to stay with my current partner and will I still be able to grow spiritually with him?',
        'I got a proposal from my boyfriend. Should I agree? Will our marriage be happy?',
        'How to get rid in a right way of a guy who is in love with me but I feel nothing for him?',
        'I just broke up with my boyfriend, but I really want him back. Is he my future husband and does he still love me?',
        'Do I need to worry about anything from his past? Can I trust him? Is he a good person?',
        'I think that I fell in love with my colleague. Should I tell him about my feelings? Is it a right time?',
        'Should I message him and tell that i miss him? Is that a good idea? Would it bring him to me faster?',
        'Is it good idea to go for a date tomorrow with...?',
        'Will I marry a millionaire?',
        'Will I get pregnant this year?',
        'What name should I choose for my first child? Could you advise me on how to select it?',
        'I\'m in love with a married man. He says taht he is divorcing soon. Is it really so? Will he be with me or stays with his wife?',
        'I and my boyfriend are in different locations now. Will we be together anyway?',
        'Can you check if my boyfriend is being faithful?',
        'I met a guy from the internet and he asked me out for a date. Should I agree? How can I trust him?',
        'Does the guy I met today likes me as more than a friend?',
        'Can I trust him to be faithful even before we are officially in a relationship? How do I know that?',
        'Every time I get to a point where it feels we are getting closer, it seems he pull back, why does he do that?',
        'Can I and my boyfriend ever manage to understand each other?',
        'Can I trust my boyfriend and let him spend separately the upcoming holidays?',
        'I have issues with my marriage. I am not happy with our relationship. Would I find happiness in another relationship or should I stay in the marriage?',
        'I am a divorce. Will I marry again? When?',
        'How many children will I have during my whole life?',
        'I am single right now and afraid if I agree for the relationship it will prevent my career growth, what should I do?',
        'What date is the best for my wedding this year?',
        'I and my future husband are from different cities, which city should we choose for the wedding ceremony?',
        'Does my boyfriend love me as much as I do or he is with me just because of comfort and good financial situation?'
      ],
      iconData: Icons.favorite_border),
  IdeaModel('Everyday life', [], iconData: Icons.card_giftcard),
  IdeaModel('Education', [], iconData: Icons.book),
  IdeaModel('Work', [], iconData: Icons.work),
  IdeaModel('Money', [], iconData: Icons.monetization_on),
  IdeaModel('Business', [], iconData: Icons.business),
];
